// Generated by CoffeeScript 1.10.0
var fs, fsExtra, jsdom, prompt, setPath, startConvert;

jsdom = require('jsdom');

fs = require('fs');

fsExtra = require('fs-extra');

prompt = require('prompt');

setPath = function() {
  prompt.start();
  return prompt.get(['PATHURL', 'AdServer'], function(err, result) {
    console.log(result.AdServer);
    startConvert(result.PATHURL, result.AdServer);
  });
};

startConvert = function(pathURL, adServer) {
  var destAdserver, srcAdserver;
  if (adServer === 'admotion') {
    destAdserver = pathURL + '\\' + adServer;
    srcAdserver = 'templates/Admotion/Banner';
    console.log('admotion');
  }
  if (adServer === 'atlas') {
    srcAdserver = 'templates/atlas';
    destAdserver = pathURL + '\\' + adServer;
    console.log('atlas');
  }
  fsExtra.copy(srcAdserver, destAdserver, function(err) {
    if (err) {
      return console.error(err);
    }
    return console.log('success! paste');
  });
  return console.log(destAdserver);
};

setPath();
