// Generated by CoffeeScript 1.10.0
var Route, homeController;

homeController = require('./controllers/home');

Route = (function() {
  function Route(app) {
    app.get('/', homeController.get);
  }

  return Route;

})();

module.exports = Route;
