// Generated by CoffeeScript 1.10.0
var Route, compress, compressController, home, homeController;

homeController = require('./controllers/home');

home = new homeController;

compressController = require('./controllers/compress');

compress = new compressController;

Route = (function() {
  function Route(app) {
    app.post('/api', home.post);
    app.post('/compress', compress.post);
  }

  return Route;

})();

module.exports = Route;
