// Generated by CoffeeScript 1.8.0
var Route, app, express, port, route;

express = require('express');

Route = require('./route');

app = new express;

route = new Route(app);

app.use(express["static"]('static'));

port = process.env.PORT || 4000;

app.listen(port);

console.log("server running on port " + port);
