// Generated by CoffeeScript 1.10.0
var Api;

Api = (function() {
  function Api() {}

  Api.prototype.get = function(req, res) {
    res.send('API');
  };

  return Api;

})();

module.exports = Api;
