// Generated by CoffeeScript 1.10.0
var CompressImg, Home, fs;

CompressImg = require('../classes/compress_img');

fs = require('fs');

Home = (function() {
  function Home() {
    this.compress = new CompressImg;
  }

  Home.prototype.post = function(req, res) {
    return res.writeHead(200);
  };

  return Home;

})();

module.exports = Home;
