// Generated by CoffeeScript 1.10.0
var CompressImg, Home, compress, formidable, fs, path, util;

CompressImg = require('../classes/compress_img');

fs = require('fs');

formidable = require('formidable');

path = require('path');

util = require('util');

compress = new CompressImg;

Home = (function() {
  function Home() {
    this.compress = new CompressImg;
  }

  Home.prototype.post = function(req, res) {
    var fields, form;
    fields = [];
    form = new formidable.IncomingForm();
    form.multiples = true;
    form.uploadDir = path.join('./', '/uploads');
    form.on('file', function(field, file) {
      fs.rename(file.path, path.join(form.uploadDir, file.name));
    });
    form.on('field', function(field, value) {
      fields[field] = value;
    });
    form.on('error', function(err) {
      console.log('An error has occured: \n' + err);
    });
    form.on('end', function() {
      res.write('received the data:\n\n');
      res.end(util.inspect({
        fields: fields
      }));
      console.log(fields.fields);
      compress.startImagemin(fields.fields);
    });
    form.parse(req);
  };

  return Home;

})();

module.exports = Home;
