// Generated by CoffeeScript 1.10.0
var Home;

Home = (function() {
  function Home() {}

  Home.prototype.get = function(req, res) {
    res.writeHead(200, {
      'Content-Type': 'text/html'
    });
    res.write('teste');
    res.end();
  };

  return Home;

})();

module.exports = Home;
