// Generated by CoffeeScript 1.10.0
var CompressImg, gulp, imagemin, pngquant;

gulp = require('gulp');

imagemin = require('gulp-imagemin');

pngquant = require('imagemin-pngquant');

CompressImg = (function() {
  function CompressImg() {}

  CompressImg.prototype.startImagemin = function(quality, uuid) {
    var defaultQuality, highQuality, lowQuality, middleQuality;
    lowQuality = '5-15';
    middleQuality = '50-65';
    highQuality = '65-80';
    defaultQuality = '90-100';
    console.log(quality[0]);
    switch (quality[0]) {
      case 'low':
        quality = lowQuality;
        break;
      case 'middle':
        quality = middleQuality;
        break;
      case 'high':
        quality = highQuality;
        break;
      default:
        quality = defaultQuality;
    }
    return gulp.src("./uploads/" + uuid + "/*").pipe(imagemin({
      progressive: true,
      svgoPlugins: [
        {
          removeViewBox: false
        }, {
          cleanupIDs: false
        }
      ],
      use: [
        pngquant({
          quality: quality,
          speed: 4
        })
      ]
    })).pipe(gulp.dest("./compress/" + uuid));
  };

  return CompressImg;

})();

module.exports = CompressImg;
