// Generated by CoffeeScript 1.10.0
var CompressImg, gulp, imagemin, pngquant;

gulp = require('gulp');

imagemin = require('gulp-imagemin');

pngquant = require('imagemin-pngquant');

CompressImg = (function() {
  function CompressImg() {}

  CompressImg.prototype.startImagemin = function() {
    var defaultQuality, highQuality, lowQuality, middleQuality;
    lowQuality = '5-15';
    middleQuality = '50-65';
    highQuality = '65-80';
    defaultQuality = '90-100';
    switch (result.quality) {
      case 'low':
        result.quality = lowQuality;
        break;
      case 'middle':
        result.quality = middleQuality;
        break;
      case 'high':
        result.quality = highQuality;
        break;
      default:
        result.quality = defaultQuality;
    }
    return gulp.src(callback + '/*').pipe(imagemin({
      progressive: true,
      svgoPlugins: [
        {
          removeViewBox: false
        }, {
          cleanupIDs: false
        }
      ],
      use: [
        pngquant({
          quality: quality,
          speed: 4
        })
      ]
    })).pipe(gulp.dest(callback + '/compress'));
  };

  return CompressImg;

})();

module.exports = CompressImg;
