// Generated by CoffeeScript 1.10.0
var ConvertTemplate, fs, fsExtra, glob, jsdom, mkdirp, path, prompt;

jsdom = require('jsdom');

fs = require('fs');

fsExtra = require('fs-extra');

prompt = require('prompt');

glob = require('glob');

path = require('path');

mkdirp = require('mkdirp');

ConvertTemplate = (function() {
  function ConvertTemplate() {}

  ConvertTemplate.prototype.startMultipleConvertions = function(vehicles, uuid) {
    var i, vehicle;
    i = 0;
    while (i < vehicles.length) {
      vehicle = vehicles[i];
      this.startConvert(vehicle, uuid);
      i++;
    }
  };

  ConvertTemplate.prototype.startConvert = function(adServer, uuid) {
    var destAdserver, pathIMGS, srcAdserver;
    switch (adServer) {
      case 'htmlLimpo':
        srcAdserver = './templates/html_limpo';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'abril':
        srcAdserver = './templates/abril';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'admotion':
        srcAdserver = './templates/Admotion/Banner';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = destAdserver + "/custom/images/";
        break;
      case 'afilio':
        srcAdserver = './templates/afilio';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'atlas':
        srcAdserver = './templates/atlas_by_facebook';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'buscape':
        srcAdserver = './templates/buscape';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'cbn':
        srcAdserver = './templates/cbn';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'dbcm':
        srcAdserver = './templates/dbcm';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'dbcm_loop':
        srcAdserver = './templates/dbcm_loop';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'dcm_africa':
        srcAdserver = './templates/dcm_africa';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'dcm_africa_loop':
        srcAdserver = './templates/dcm_africa_loop';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'dcStudio':
        srcAdserver = './templates/dcm_africa_loop';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'estadao':
        srcAdserver = './templates/estadao';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'gdnAdword':
        srcAdserver = './templates/gdnAdword';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'gdnAdword_loop':
        srcAdserver = './templates/gdnAdword_loop';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'globo':
        srcAdserver = './templates/globo';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'ig':
        srcAdserver = './templates/ig';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'infomoney':
        srcAdserver = './templates/infomoney';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'mercadoEventos':
        srcAdserver = './templates/mercadoEventos';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'mercadoLivre':
        srcAdserver = './templates/mercadoLivre';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'msn':
        srcAdserver = './templates/msn';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'nzn':
        srcAdserver = './templates/nzn';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'r7':
        srcAdserver = './templates/r7';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'sizmek':
        srcAdserver = './templates/sizmek';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'smartclip':
        srcAdserver = './templates/smartclip';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'sociomantic':
        srcAdserver = './templates/sociomantic';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'techmundo':
        srcAdserver = './templates/techmundo';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'terra':
        srcAdserver = './templates/terra';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
        break;
      case 'uol':
        srcAdserver = './templates/uol';
        destAdserver = "./convert/" + uuid + "/" + adServer;
        pathIMGS = "" + destAdserver;
    }
    mkdirp("" + destAdserver, function(err) {
      if (err) {
        console.error(err);
      } else {
        console.log('Done!');
      }
    });
    console.log(destAdserver);
    fsExtra.copy(srcAdserver, destAdserver, function(err) {
      var extension, htmlSource, htmlSourceTemplate, j, len, ref, sourceHTML, sourceTemplate;
      if (err) {
        return console.error(err);
      }
      console.log('success! paste');
      ref = ['*.jpg', '*.png', '*.gif'];
      for (j = 0, len = ref.length; j < len; j++) {
        extension = ref[j];
        glob("./uploads/" + uuid + "/" + extension, null, function(err, files) {
          var file, k, len1;
          if (err) {
            return console.error(err);
          }
          for (k = 0, len1 = files.length; k < len1; k++) {
            file = files[k];
            console.log(file);
            if (adServer === 'admotion') {
              fsExtra.copy(file, destAdserver + "/custom/images/" + (path.basename(file)), function(err) {});
              if (err) {
                return console.error(err);
              }
            } else {
              fsExtra.copy(file, destAdserver + "/" + (path.basename(file)), function(err) {
                if (err) {
                  return console.error(err);
                }
              });
            }
          }
        });
      }
      htmlSource = fs.readFileSync("./uploads/" + uuid + "/index.html", 'utf8');
      htmlSourceTemplate = fs.readFileSync(destAdserver + "/index.html", 'utf8');
      sourceHTML = jsdom.jsdom(htmlSource, {
        features: {
          FetchExternalResources: ['script'],
          ProcessExternalResources: ['script'],
          MutationEvents: '2.0'
        },
        parsingMode: 'auto'
      });
      sourceTemplate = jsdom.jsdom(htmlSourceTemplate, {
        features: {
          FetchExternalResources: ['script'],
          ProcessExternalResources: ['script'],
          MutationEvents: '2.0'
        },
        parsingMode: 'auto'
      });
      jsdom.jQueryify(sourceHTML.defaultView, 'http://code.jquery.com/jquery.js', function() {
        var $, contentBanner, contentCssBanner, contentCssBannerOveflow, contentUrlDestino, creativityHeight, creativityWidth, cssBanner, cssBannerLength, elementClickTag, fnc, l, urlDestino;
        $ = sourceHTML.defaultView.$;
        contentBanner = $('#page1').parent().html();
        creativityWidth = $('#page1').attr('data-gwd-width');
        creativityHeight = $('#page1').attr('data-gwd-height');
        console.log(creativityWidth);
        console.log(creativityHeight);
        urlDestino = $('gwd-exit').attr('url');
        console.log(urlDestino);
        cssBanner = $('style');
        contentCssBannerOveflow = "<style>#page1{overflow:hidden}</style>";
        contentUrlDestino = '<script>var clickTag = "' + ("" + urlDestino) + '"</script>';
        cssBannerLength = cssBanner.length;
        l = 0;
        while (l < cssBannerLength) {
          contentCssBanner = cssBanner[l].outerHTML;
          l++;
        }
        elementClickTag = '<style>#clickTagArea{position:absolute; width:' + ("" + creativityWidth) + '; height:' + ("" + creativityHeight) + ';left:0;top:0;cursor:pointer;}</style>';
        fnc = (function(css, banner) {
          return function() {
            var bannerDimensions, bannerHeight, bannerWidth, bodyTemplate, contentTemplate, headerTemplate, page, removeScript, replaceImg;
            $ = sourceTemplate.defaultView.$;
            headerTemplate = $('head');
            if (adServer === 'admotion') {
              contentTemplate = $('#Creativity');
            } else {
              contentTemplate = $('body');
            }
            bodyTemplate = $('body');
            page = $('#page1');
            page.addClass(' gwd-play-animation');
            if (adServer === 'admotion') {
              bannerDimensions = $('#bannerDimensions');
              bannerDimensions.html('var adConfig = {}; adConfig.creativityWidth = "' + ("" + creativityWidth) + '"; adConfig.creativityHeight = "' + ("" + creativityHeight) + '";');
            }
            bodyTemplate.append('<script> window.onload = function(){ var bannerOutput = document.getElementById("page1"); bannerOutput.className += " gwd-play-animation"; } </script>');
            headerTemplate.append(contentCssBannerOveflow);
            headerTemplate.append(contentCssBanner);
            headerTemplate.append(elementClickTag);
            headerTemplate.prepend(contentUrlDestino);
            contentTemplate.prepend(contentBanner);
            replaceImg = $('img[is="gwd-image"]').each(function(index, data) {
              var source, tag;
              tag = $(data);
              source = tag.attr('source');
              tag.removeAttr('is');
              tag.removeAttr('id');
              tag.removeAttr('source');
              if (adServer === 'admotion') {
                tag.attr('src', 'custom/images/' + source);
              } else {
                tag.attr('src', source);
              }
            });
            removeScript = $('.jsdom');
            removeScript.remove();
            bannerWidth = parseInt("" + creativityWidth);
            bannerHeight = parseInt("" + creativityHeight);
            fs.writeFile(destAdserver + "/index.html", '<html>' + contentTemplate.parents('html').html() + '</html>', function(err) {
              var filePath;
              if (err) {
                throw err;
              }
              console.log('Template Convertido com sucesso.');
              fs.rename("" + destAdserver, destAdserver + "_" + bannerWidth + "x" + bannerHeight, function(err) {
                if (err) {
                  throw err;
                }
                console.log('renamed complete');
              });
              return filePath = './uploads/';
            });
          };
        })(contentCssBanner, contentBanner);
        jsdom.jQueryify(sourceTemplate.defaultView, 'http://code.jquery.com/jquery.js', fnc);
      });
    });
  };

  return ConvertTemplate;

})();

module.exports = ConvertTemplate;
