// Generated by CoffeeScript 1.10.0
var ToolBox;

ToolBox = (function() {
  function ToolBox() {
    console.log('toolbox');
  }

  ToolBox.prototype.method1 = function() {
    return console.log('toolbox method1');
  };

  ToolBox.prototype.methdo2 = function() {
    return console.log('toolbox method2');
  };

  return ToolBox;

})();

module.exports = ToolBox;
